# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[32,)" #mandatory

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/KurodaAkira/RPG-Hud/issues" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/rpg-hud" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="rpg-hud" #mandatory

# A text field displayed in the mod UI
authors="KurodaAkira" #optional

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="3.7.1" #mandatory

 # A display name for the mod
displayName="RPG-Hud" #mandatory

# The description text for the mod (multi line!) (#mandatory)
description='''
This mod changes the way the HUD is rendered and adds several new functionalities and styles (mainly RPG-like styles)
'''